// src/components/RoleMap/RoleMap.jsx
import React from "react";
import "./RoleMap.css";
import "./../EshAssumptions/EshAssumptions.css"
import TitleCardHeader from "../DepartmentSelect/TitleCardHeader/TitleCardHeader.jsx";
import AccentStripe from "../HomeScreen/AccentStripe/AccentStripe.jsx";
import StandardButton from "../StandardButton/StandardButton.jsx";
import RoleRow from "./RoleRow/RoleRow.jsx";
import useConfigDeletion from "../../utils/useConfigDeletion.js";
import {buildUpdateString} from "../../utils/buildUpdateString.js";


export default function RoleMap({ onClose }) {
  const [settings, setSettings] = React.useState(null);
  const [dept, setDept] = React.useState("");
  const [rows, setRows] = React.useState([]); // [{raw, display, enabled}, ...]
  const [loading, setLoading] = React.useState(false);
  const { handleDeleteConfigKey } = useConfigDeletion(setLoading, setSettings);

  const deptList = React.useMemo(() => {
    if (!settings?.ROLE_MAP) return [];
    return Object.keys(settings.ROLE_MAP).filter((k) => k !== "Blacklists");
  }, [settings]);

  function toRows(roleMapDept) {
    const roles = roleMapDept?.roles || [];
    const clean = roleMapDept?.clean_roles || [];
    const en    = roleMapDept?.labor_tracker_enabled || [];
    const len   = Math.max(roles.length, clean.length, en.length);
    const out = [];
    for (let i = 0; i < len; i++) {
      out.push({
        raw: roles[i] ?? "",
        display: clean[i] ?? (roles[i] ?? ""),
        enabled: Boolean(en[i] ?? 1),
      });
    }
    return out;
  }

  function fromRows(rs) {
    return {
      roles: rs.map(r => r.raw),
      clean_roles: rs.map(r => r.display),
      labor_tracker_enabled: rs.map(r => (r.enabled ? 1 : 0)),
    };
  }

  React.useEffect(() => {
    let alive = true;
    (async () => {
      const cfg = await window.electronAPI.readSettings();
      if (!alive) return;
      setSettings(cfg);
      const first = Object.keys(cfg?.ROLE_MAP || {}).find(k => k !== "Blacklists") || "";
      setDept(first);
      setRows(toRows(cfg?.ROLE_MAP?.[first]));
    })();
    return () => { alive = false; };
  }, []);

  React.useEffect(() => {
    if (!settings || !dept) return;
    setRows(toRows(settings.ROLE_MAP?.[dept]));
  }, [settings, dept]);

  function updateRow(index, next) {
    setRows(rows.map((r, i) => (i === index ? next : r)));
  }
  function removeRow(index) {
    setRows(rows.filter((_, i) => i !== index));
  }
  function addRow(raw, display) {
    setRows([...rows, { raw, display, enabled: true }]);
  }
  function moveUp(index) {
    if (index <= 0) return;
    const copy = rows.slice();
    [copy[index - 1], copy[index]] = [copy[index], copy[index - 1]];
    setRows(copy);
  }
  function moveDown(index) {
    if (index >= rows.length - 1) return;
    const copy = rows.slice();
    [copy[index + 1], copy[index]] = [copy[index], copy[index + 1]];
    setRows(copy);
  }
  async function deleteDepartment() {
    if (!dept) return; 

    const keyToDelete = dept;
      if (keyToDelete === "Blacklists") {
        console.warn("Attempted to delete Blacklists. Action blocked.");
        return; 
  }
    const message = `Are you sure you want to delete the department "${keyToDelete}"?\n This will remove its Role Map AND its Time Blocks.\n This action is immediate and cannot be undone.\n Settings can be regenerated by parsing a schedule.`;
    
    // --- Step A: Delete the ROLE_MAP entry (Handles the user prompt) ---
    const roleMapPathSegments = ["ROLE_MAP", keyToDelete];
    const roleMapSuccess = await handleDeleteConfigKey(roleMapPathSegments, keyToDelete, message);

    if (!roleMapSuccess) {
      // If the first deletion (Role Map) fails or is cancelled, stop.
      return; 
    }

    // --- Step B: Delete the TIME_BLOCKS entry ---
    const timeBlocksPathSegments = ["TIME_BLOCKS", keyToDelete];
    // Pass null for the message to avoid re-prompting the user
    // The hook will update settings upon successful deletion.
    const timeBlockSuccess = await handleDeleteConfigKey(timeBlocksPathSegments, keyToDelete, null);
    
    // --- Step C: Cleanup and state update ---
    if (timeBlockSuccess) {
      // Important: Since the hook updates settings, we use the now-updated state
      // to determine the next department to select. We need a fresh copy of settings
      // that reflects the deletion for correct UI update.
      const updatedSettings = await window.electronAPI.readSettings();
      setSettings(updatedSettings); // Ensure final state is correct

      const newDeptList = Object.keys(updatedSettings?.ROLE_MAP || {}).filter(k => k !== "Blacklists");
      const nextDept = newDeptList[0] || ""; 
      
      // Update the selected department, which triggers the useEffect to update 'rows'
      setDept(nextDept);
    }
    // Note: If TimeBlocks fails but RoleMap succeeded, the user will still see the RoleMap gone,
    // and the TimeBlocks will remain in the config (a manual fix may be needed later).
  }  
  async function save() {
    if (!dept) {
        console.warn("Save blocked: No department selected.");
        onClose?.(); // Optionally close the panel
        return;
    }
    const payload = fromRows(rows);
    const update = buildUpdateString(["ROLE_MAP", dept], payload, "update");

    try {
      setLoading(true);
      const fresh = await window.electronAPI.readSettings();
      await window.electronAPI.applyConfig(update);
      setSettings(fresh);
    
      setTimeout(() =>{
        onClose?.();
        setLoading(false);
      }, 1000); 
    } catch (e) {
      console.error("applyConfig (RoleMap) failed:", e);
    }
  }

  if (!settings) return null;

  return (
    <div className="rm-card">
      <TitleCardHeader title="Role Map" />
      <AccentStripe />

      <div className="rm-toolbar">
        <select
          className="rm-select"
          value={dept}
          onChange={(e) => setDept(e.target.value)}
          aria-label="Select department"
        >
          {deptList.map((d) => (
            <option key={d} value={d}>{d}</option>
          ))}
        </select>
        {dept && deptList.length > 0 && ( // Conditional rendering: Must have a department selected
          <StandardButton
            className = "rm-mini danger"
            label = "-" 
            onClick = {deleteDepartment}
            disabled = {loading}
          />
        )}
      </div>

      <div className="rm-rows">
        {rows.map((r, i) => (
          <RoleRow
            key={`${r.raw}-${i}`}
            data={r}
            onChange={(next) => updateRow(i, next)}
            onRemove={() => removeRow(i)}
            onUp={() => moveUp(i)}
            onDown={() => moveDown(i)}
          />
        ))}
      </div>

      <div className="settings-footer">
              <StandardButton
              label = "Cancel"
              onClick = {onClose}
              />
              <div className = "settings-spacer" />
              <StandardButton
                label = {loading ? "Saving..." : "Save & Close"}
                onClick = {save}
                disabled = {loading || !dept}
              />
      </div>
    </div>
  );
}